include:
    # Include some default job templates for various job types
    - project: 'codebreeze-io/project-template/gitlab-gradle-template'
      file: '.gitlab-micro-stageless-pipeline.yml'
      ref: feature/modular-jobs
    - project: 'codebreeze-io/project-template/gitlab-gradle-template'
      file: 'workflow/.gitlab-auto-tag-delivery-workflow.yml'
      ref: feature/modular-jobs
    - project: 'codebreeze-io/project-template/gitlab-gradle-template'
      file: 'workflow/.gitlab-mergerequest-then-branch-or-tag-workflow.yml'
      ref: feature/modular-jobs

variables:
    DOCKER_DRIVER: overlay2
    GRADLE_OPTS:
        value: -Dorg.gradle.daemon=false -Dorg.gradle.caching=true -Dorg.gradle.project.reckon.enabled=true
        description: "Common Gradle options"
    DELIVER_JOB_GRADLE_TASK:
        value: 'deliver'
        description: 'Default Gradle task for the deliver job'

check:
    variables:
        POSTGRESQL_USERNAME: spring
        POSTGRESQL_PASSWORD: boot
        POSTGRESQL_DATABASE: app
        SPRING_DATASOURCE_URL: jdbc:postgresql://postgresql/app
        SPRING_DATASOURCE_USERNAME: spring
        SPRING_DATASOURCE_PASSWORD: boot
        SPRING_JPA_GENERATE_DDL: "true"
    services:
        - name: bitnami/postgresql:11
          alias: postgresql
    script:
        - !reference [ .check-script,script ]
        - !reference [ .create-version-dotenv, script ]
    artifacts:
        !reference [ .create-version-dotenv, artifacts ]

deliver:
    services:
        - docker:19-dind
