stages:
  - build
  - deploy

cache:
  key: ${CI_JOB_NAME}
  paths:
  - /root/.gradle

build:
  stage: build
  image: adoptopenjdk:11-jdk-hotspot
  script:
    - ./gradlew --no-daemon buildDockerContext
  artifacts:
    paths:
      - build/

deliver:
  stage: deploy
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR/build/docker/app --dockerfile $CI_PROJECT_DIR/build/docker/app/Dockerfile --destination $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
  only:
    - tags
  dependencies:
    - build
   