stages:
    - build
    - deliver

cache:
    key: ${CI_JOB_NAME}
    paths:
        - /root/.gradle

build:
    stage: build
    image: adoptopenjdk:11-jdk-hotspot
    script:
        - ./gradlew --no-daemon buildDockerContext
    artifacts:
        paths:
            - build/
# TODO pass branch/tag as project.version
deliver:
    stage: deliver
    image: adoptopenjdk:11-jdk-hotspot
    script:
        - ./gradlew --no-daemon publishBootJavaPublicationToGitLabRepository
    artifacts:
        paths:
            - build/
#    only:
#        - tags
    dependencies:
        - build
