variables:
  DOCKER_DRIVER: overlay2
  GRADLE_OPTS:
    value: -Dorg.gradle.daemon=false -Dorg.gradle.caching=true -Dorg.gradle.project.reckon.enabled=true
    description: "Common Gradle options"
  DEFAULT_JOB_IMAGE_NAME:
    value: eclipse-temurin:17-jdk-alpine

include:
    # Include some default job templates for various job types
    - project: 'codebreeze-io/project-template/gitlab-template'
      ref: '0.4'
      file:
        - 'gradle/micro-stageless-pipeline.gitlab-ci.yml'
        - 'rule/deliver-job-auto-tag-rule.gitlab-ci.yml'
        - 'workflow/mergerequest-then-branch-or-tag-workflow.gitlab-ci.yml'
        # Add the release feature for this pipeline
        - 'release/release-micro-stageless-pipeline.gitlab-ci.yml'

check:
    variables:
        POSTGRESQL_USERNAME: spring
        POSTGRESQL_PASSWORD: boot
        POSTGRESQL_DATABASE: app
        SPRING_DATASOURCE_URL: jdbc:postgresql://postgresql/app
        SPRING_DATASOURCE_USERNAME: spring
        SPRING_DATASOURCE_PASSWORD: boot
        SPRING_JPA_GENERATE_DDL: "true"
    services:
        - name: bitnami/postgresql:11
          alias: postgresql

deliver:
    services:
        - docker:19-dind
