spring:
  data:
    rest:
      base-path: /api
  hateoas:
    use-hal-as-default-json-media-type: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
    enabled-by-default: true
  info:
    git:
      enabled: true
      mode: full
    build:
      enabled: true

banner:
  location: banner.txt

server:
  forward-headers-strategy: framework
logging:
  level:
    root: info
    org.springframework.boot: debug
