version: '2'

services:
  # Run integration test against the app
  integration:
    image: openjdk:8-jdk
    volumes:
      - ${PROJECT_DIR}:/project
      - dot_gradle:/root/.gradle
    working_dir: "/project"
    command: "bash -c \"./gradlew integrationTest\""
    environment:
      - TEST_SERVER_HOST=${APP_HOST}
      - TEST_SERVER_PORT=${APP_PORT}
    depends_on:
      - app

volumes:
  dot_gradle:
    external: true