version: '2'

services:

  # Prepare docker context (Dockerfile, compose scripts, Spring Boot JAR)
  build:
    image: openjdk:8-jdk
    volumes:
      - ${PROJECT_DIR}:/project
      - dot_gradle:/root/.gradle
    working_dir: "/project"
    command: "bash -c \"./gradlew clean localIntegrationTest asciidoctor assemble buildDockerContext\""

volumes:
  dot_gradle:
    external: true