version: '2.1'

services:
  # Prepare docker context (Dockerfile, compose scripts, Spring Boot JAR)
  build:
    extends:
        file: pipeline-stage-base.yml
        service: stage-base
    command: 'bash -c "./gradlew --no-daemon -Prelease.scope=patch -Prelease.stage=milestone clean asciidoctor assemble buildDockerContext"'

  releaseInfo:
    extends:
            file: pipeline-stage-base.yml
            service: stage-base
    command: 'bash -c "./gradlew --no-daemon --quiet -Prelease.scope=patch -Prelease.stage=milestone dumpVersion"'

  release:
    extends:
            file: pipeline-stage-base.yml
            service: stage-base
    environment:
      - GRGIT_USER
      - GRGIT_PASSWORD
    # passing the git credentials as system properties is a workaround, env variables should be sufficient
    command: 'bash -c "./gradlew --no-daemon --quiet -Prelease.scope=patch -Prelease.stage=milestone -Dorg.ajoberstar.grgit.auth.force=hardcoded -Dorg.ajoberstar.grgit.auth.username=$GRGIT_USER -Dorg.ajoberstar.grgit.auth.password=$GRGIT_PASS --stacktrace release"'

volumes:
  dot_gradle:
    external: true
