version: '2'

services:
  stage-base:
    image: openjdk:8-jdk
    environment:
      - GRADLE_OPTS
    volumes:
      - ${PROJECT_DIR}:/project
      - dot_gradle:/root/.gradle
    working_dir: "/project"
