version: '2'

services:
  # Prepare docker context (Dockerfile, compose scripts, Spring Boot JAR)
  build:
    extends:
        file: pipeline-stage-base.yml
        service: stage-base
    command: "bash -c \"./gradlew clean asciidoctor assemble buildDockerContext\""

volumes:
  dot_gradle:
    external: true
