version: '2'

services:
  # Run integration test against the app
  integration-test:
    extends:
        file: pipeline-stage-base.yml
        service: stage-base
    command: 'bash -c "./gradlew --no-daemon integrationTest"'
    environment:
      - TEST_SERVER_HOST=${APP_HOST}
      - TEST_SERVER_PORT=${APP_PORT}
    depends_on:
      - app
         #condition: service_healthy
    networks:
      - app

volumes:
  dot_gradle:
    external: true
