apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-postgresdb
  labels:
    app: {{ .Release.Name }}-postgresdb
spec:
  ports:
  - port: 5432
    protocol: TCP
  selector:
    app: {{ .Release.Name }}-postgresdb