kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgresdb-volume
  labels:
    type: local
spec:
  storageClassName: local
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  local:
    path: /var/volume/postgresdb
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - docker01
