apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresdb-pvc
  labels:
    app: postgresdb
spec:
  storageClassName: local-storage
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
