apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresdb-data
  labels:
    app: postgresdb-data
spec:
  storageClassName: local
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
