= README

== Kubernetes


=== Context Configuration

kubectl configuration
export KUBECONFIG=$HOME/.kube/config:$HOME/.kube/docker01.software-craftsmen.at


=== Connect to minikube

minikube start --vm-driver=xhyve
eval $(minikube docker-env)


=== Build application
export DOCKER_REGISTRY=softwarecraftsmen/
export APP_TAG=1.0 #set proper version number
cd build/docker
docker-compose build

=== push to Docker Hub

docker login --username softwarecraftsman
docker image tag continuousdelivery-app:1.0 softwarecraftsmen/continuousdelivery-app:1.0
docker push softwarecraftsmen/continuousdelivery-app:1.0
docker image tag continuousdelivery-postgresdb:1.0 softwarecraftsmen/continuousdelivery-postgresdb:1.0


=== kubectl imperative

kubectl run continuousdelivery-app --image=continuousdelivery-app:${APP_TAG} --port=8080
kubectl proxy # in an new terminal

export POD_NAME=$(kubectl get pods -o go-template --template '{{range .items}}{{.metadata.name}}{{"\n"}}{{end}}')
echo Name of the Pod: $POD_NAME
kubectl logs $POD_NAME -f

kubectl get deployment continuousdelivery-app -o yaml --export

open http://localhost:8001/api/v1/namespaces/default/pods/$POD_NAME/proxy/api

=== kubectl declarative

cd src/main/kubernetes

kubectl apply -f datasource_secret.yaml
kubectl apply -f postgresdb-data-persistentvolumeclaim.yaml
kubectl apply -f postgresdb-persistentvolumeclaim.yaml
kubectl apply -f postgresdb-deployment.yaml
kubectl apply -f postgresdb-service.yaml
kubectl apply -f app-deployment.yaml
kubectl apply -f app-service.yaml

=== Nginx ingress

minikube addons enable ingress

kubectl apply -f app-ingress.yaml

echo "$(minikube ip) continuousdelivery.minikube" | sudo tee -a /etc/hosts
open http://continuousdelivery.minikube


== Helm

=== Client Installation

brew install kompose
brew install kubernetes-helm

=== Kubernetes Configuration

helm init

