# See README.adoc for instructions on completing the configuration of the docker-registry

version: "2.1"

services:
  repository:
    ports:
      - ${NEXUS_DOCKER_REGISTRY_PORT}:5000
    volumes:
      - docker-data:/nexus-docker-data

volumes:
  docker-data: {}
