version: '2'

services:
  master:
    image: softwarecraftsmen/jenkins-master:${JENKINS_TAG}
    restart: always
    environment:
      - JAVA_OPTS = "-Djava.awt.headless=true"
      - JENKINS_URL
      - JENKINS_ADMIN_USERNAME
      - JENKINS_ADMIN_PASSWORD
    ports:
      - "${JENKINS_HTTP_PORT}:8080"
    volumes:
      - home:/var/jenkins_home/

volumes:
  home:
    driver: local
