version: '2.1'

services:
  master:
    image: softwarecraftsmen/jenkins-master:${JENKINS_TAG}
    build: ./jenkins
    restart: always
    environment:
      - JAVA_OPTS = "-Djava.awt.headless=true"
      - JENKINS_URL
      - JENKINS_ADMIN_USERNAME
      - JENKINS_ADMIN_PASSWORD
      - JENKINS_GLOBAL_PROPERTIES_IMPORT
      - DOCKER_REGISTRY
      - GRADLE_OPTS
      - SCM_USER
      - SCM_PASSWORD
      - DOCKER_REGISTRY_USER
      - DOCKER_REGISTRY_PASSWORD
    ports:
      - "${JENKINS_HTTP_PORT}:8080"
    volumes:
      - home:/var/jenkins_home/
    healthcheck:
      test: ["CMD", "curl", "-f", "http://master:8080/login"]
      timeout: 5s

volumes:
  home:
    driver: local

networks:
  default:
    driver: bridge
