version: "2.1"

services:
  repository:
    image: sonatype/nexus3:${NEXUS_TAG}
    ports:
      - ${NEXUS_HTTP_PORT}:8081
    restart: always
    volumes:
      - data:/nexus-data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://repository:8081"]
      timeout: 5s

volumes:
  data: {}
