= README

== Common setup

The following `docker-compose` command are assuming the following environment variable definitions in `.env`:

[source,bash]
----
COMPOSE_PROJECT=infrastructure
COMPOSE_HTTP_TIMEOUT=300
----

== Run Jenkins

This runs a Jenkins master and agent.

[source,bash]
----
export JENKINS_AGENT_WORKSPACE=/workspace
export JENKINS_AGENT_EXECUTORS=5
docker-compose -f jenkins-master.yml -f jenkins-agent.yml up -d
----

[IMPORTANT]
--
The `workspace` directory must exist on the Docker host. Create it before if using a docker-machine managed host:
`docker-machine ssh <machine-id> "mkdir /workspace"`
--

=== Use local Jenkins workspace with Docker for Mac/Windows

[source,bash]
----
export JENKINS_AGENT_WORKSPACE=$PWD/workspace
docker-compose -f jenkins-master.yml -f jenkins-agent.yml up -d
----

=== Use local source repositories

Add and load an additional docker-compose configuration such as:

[source,bash]
----
include::local-repositories.yml[linenums]
----

[source,bash]
----
docker-compose -f jenkins-master.yml -f jenkins-agent.yml -f local-repositories.yml up -d
----

=== Auto-register global properties

In order to have global properties available, assign a list of variable names to the enironment variable `JENKINS_GLOBAL_PROPERTIES_IMPORT`.

[source,bash]
----
JENKINS_GLOBAL_PROPERTIES_IMPORT=GRADLE_OPTS,DOCKER_REGISTRY
----

=== Auto-register credentials

The Jenkins build pipeline requires credentials for accessing various system resources.
Set the following environment variables:

.Credential` id `scm
[source,bash]
----
SCM_USER=MartinAhrer
SCM_PASSWORD=***
----

.Credential id `dockerRegistryDeployer`
[source,bash]
----
DOCKER_REGISTRY_USER=admin
DOCKER_REGISTRY_PASSWORD=***
----

== Run Nexus

This runs a Nexus3 instance which we use as a Docker registry.

[source,bash]
----
docker-compose -f nexus.yml -f nexus-docker-registry.yml up -d
----

In order to fix permissions for the docker registry blob volume run the following command
[source,bash]
----
docker-compose exec --user root repository bash -c "chown -R nexus:nexus /nexus-docker-data/"
----

=== Configure Nexus

.Setup blob store with
|===
|Field |Value

|Type
|File

|Name
|docker-registry

|Path
|/nexus-docker-data/blobs/docker-registry
|===

.Create Docker repository and connector with
|===
|Field |Value

|Type
|docker(hosted)

|Name
|docker-local-releases

|Connector
|HTTP, port 5000

|Blob store
|docker-registry

|Deployment policy
|Disable redeploy
|===

NOTE: We disallow redeploy to avoid Docker `latest` style image tags.

=== Configure docker-daemon unsecure registry

.Add docker-registry to `/etc/hosts`
[source,bash]
----
 127.0.0.1 docker-registry
----

.Add insecure registry to daemon config
[source,bash]
----
docker-registry:15000
----
