= README

== Common setup

The following `docker-compose` command are assuming the following environment variable definitions in `.env`:

[source,bash]
----
COMPOSE_PROJECT=infrastructure
COMPOSE_HTTP_TIMEOUT=300
----

== Run Jenkins

This runs a Jenkins master and agent.

[source,bash]
----
export JENKINS_AGENT_WORKSPACE=/workspace
export JENKINS_AGENT_EXECUTORS=5
docker-compose -f docker-compose-jenkins.yml -f docker-compose-jenkins-agent.yml up -d
----

[IMPORTANT]
--
The `workspace` directory must exist on the Docker host. Create it before if using a docker-machine managed host:
`docker-machine ssh <machine-id> "mkdir /workspace"`
--

=== Use local Jenkins workspace

[source,bash]
----
export JENKINS_AGENT_WORKSPACE=$PWD/workspace
docker-compose -f docker-compose-jenkins.yml -f docker-compose-jenkins-agent.yml up -d
----

=== Use local source repositories

Add and load an additional docker-compose YML configuration such as:

[source,bash]
----
include::docker-compose-local-repositories.yml[linenums]
----

[source,bash]
----
docker-compose -f docker-compose-jenkins.yml -f docker-compose-jenkins-agent.yml -f docker-compose-local-repositories.yml up -d
----

== Run Nexus

[source,bash]
----
docker-compose -f docker-compose-nexus.yml -f docker-compose-nexus-docker-registry.yml up -d
----

=== Configure Nexus

.blob store
Type: File
Name: docker-registry:
Path: /nexus-docker-data/blobs/docker-registry

.Docker registry and connector
Type: docker(hosted),
Name: docker-local-releases,
Blob store: docker-registry,
Connector: HTTP, port 5000

.Deployment policy
Disable redeploy

=== Configure Jenkins

.Add domain "Nexus"
Name: Nexus
Description: Nexus artifact manager and docker registry

.Add credential
ID: nexus-deployer
Description: Credentials for deploying to the Docker registry

=== Configure docker-daemon unsecure registry

.Add docker-registry to /etc/hosts
----
 127.0.0.1 docker-registry
----

.Add insecure registry to daemon config
----
docker-registry:15000
----
