:toc: left

= Deployment to Hashicorp Nomad

== Runtime infrastructure

== Consul + Nomad

=== Local development instances

Run consul and nomad service from repository (TODO).
Run as many Nomad clients as required.
However, when running multiple clients you will not be able to deploy traefik to all client nodes as the traefik job configuration tries to do a static port binding.

=== Remote development instances (cluster)

Setup cluster according to https://github.com/MartinAhrer/learn-nomad-cluster-setup and https://developer.hashicorp.com/nomad/tutorials/cluster-setup.

.Install software
[source,bash]
----
brew install packer
brew install terraform
brew install --cask google-cloud-sdk
----

.Set the location of the terraform project
[source,bash]
----
TERRAFORM_GCP_PROJECT="${DEVELOPMENT_HOME}/spaces/codebreeze/learn-nomad-cluster-setup/gcp"
----

==== Google cloud

.Setup gcloud
[source,bash]
----
gcloud auth login
gcloud config set project ***
gcloud config set compute/region ***
gcloud config set compute/zone ***
----

IMPORTANT: Work in progress

== Deploy traefik

=== Local

.Deployment
[source,bash]
----
unset NOMAD_NAMESPACE
levant render -out=traefik.rendered.hcl traefik.hcl
nomad job run traefik.rendered.hcl
----

.Open traefik console
[source,bash]
----
open "http://$(ipconfig getifaddr en0).nip.io:81"
----

=== Google cloud platform

.Set nomad environment
[source,bash]
----
pushd ${TERRAFORM_GCP_PROJECT}
export NOMAD_VAR_consul_http_token="$(terraform output -raw consul_bootstrap_token_secret)"
popd
----

.Deployment
[source,bash]
----
export NOMAD_VAR_consul_http_token
unset NOMAD_NAMESPACE
levant render -out=traefik.rendered.hcl traefik.hcl
nomad job run traefik.rendered.hcl
----

IMPORTANT: Work in progress


== Deploy container application

Default configuration is for application deployment as container.

For container registry access the following variables are required to be set.
The command below expects these in a file `credentials.hcl`
(See https://developer.hashicorp.com/nomad/docs/job-specification/hcl2/variables[variables]).

* `registry_auth_username`
* `registry_auth_password`

=== Local

.Deployment
[source,bash]
----
export NOMAD_NAMESPACE="${$(git rev-parse --abbrev-ref HEAD)//\//-}"
nomad namespace apply "${NOMAD_NAMESPACE}"
nomad job run --var environment="${NOMAD_NAMESPACE}" --namespace="${NOMAD_NAMESPACE}" --var-file configuration.hcl --var-file credentials.hcl continuousdelivery.hcl
----

.Open application
[source,bash]
----
export NOMAD_NAMESPACE="${$(git rev-parse --abbrev-ref HEAD)//\//-}"
open http://continuousdelivery-api-${NOMAD_NAMESPACE}.$(ipconfig getifaddr en0).nip.io:80/api/
----

=== Google cloud platform

.Set nomad environment
[source,bash]
----
pushd ${TERRAFORM_GCP_PROJECT}
export NOMAD_VAR_api_service_domain="$(terraform output -json instance_client_ip_addresses | jq -r '.[0]').nip.io"
popd
----

.Deployment
[source,bash]
----
export NOMAD_VAR_api_service_domain
export NOMAD_NAMESPACE="${$(git rev-parse --abbrev-ref HEAD)//\//-}"
nomad namespace apply "${NOMAD_NAMESPACE}"
nomad job run --var environment="${NOMAD_NAMESPACE}" --namespace="${NOMAD_NAMESPACE}" --var-file configuration.hcl --var-file credentials.hcl continuousdelivery.hcl
----

.Open application
[source,bash]
----
export NOMAD_NAMESPACE="${$(git rev-parse --abbrev-ref HEAD)//\//-}"
open "http://continuousdelivery-api-${NOMAD_NAMESPACE}.${NOMAD_VAR_api_service_domain}:80/api/"
----

