:toc: left
:toclevels: 4

= Deployment to Hashicorp Nomad

== Runtime infrastructure

== Consul + Nomad

=== Local development instances

Run consul and nomad service from repository (TODO).
Run as many Nomad clients as required.
However, when running multiple clients you will not be able to deploy traefik to all client nodes as the traefik job configuration tries to do a static port binding.

=== Remote development instances (cluster)

Setup cluster according to https://github.com/MartinAhrer/learn-nomad-cluster-setup and https://developer.hashicorp.com/nomad/tutorials/cluster-setup.

.Install software
[source,bash]
----
brew install packer
brew install terraform
brew install --cask google-cloud-sdk
----

.Set the location of the terraform project
[source,bash]
----
export TERRAFORM_GCP_PROJECT="${DEVELOPMENT_HOME}/spaces/codebreeze/learn-nomad-cluster-setup/gcp"
----

==== Google cloud

.Setup gcloud
[source,bash]
----
gcloud auth login
gcloud config set project ***
gcloud config set compute/region ***
gcloud config set compute/zone ***
----

IMPORTANT: Work in progress

== Deploy traefik

=== Local

.Deployment
[source,bash]
----
unset NOMAD_NAMESPACE
levant render -out=traefik.rendered.hcl traefik.hcl
nomad job run traefik.rendered.hcl
----

.Open traefik console
[source,bash]
----
open "http://$(ipconfig getifaddr en0).nip.io:81"
----

=== Google cloud platform

.Set nomad environment
[source,bash]
----
pushd ${TERRAFORM_GCP_PROJECT}
export NOMAD_ADDR=$(terraform output -raw lb_address_consul_nomad):4646
export NOMAD_TOKEN=$(cat nomad_bootstrap.token)
export NOMAD_VAR_consul_http_token="$(terraform output -raw consul_bootstrap_token_secret)"
export TRAEFIK_api_service_domain="$(terraform output -json instance_client_ip_addresses | jq -r '.[0]').nip.io"
popd
----

.Deployment
[source,bash]
----
export NOMAD_VAR_consul_http_token
unset NOMAD_NAMESPACE
levant render -out=traefik.rendered.hcl traefik.hcl
nomad job run traefik.rendered.hcl
----

.Open traefik console
[source,bash]
----
open "http://${TRAEFIK_api_service_domain}:81"
----



== Deploy container workload

Default configuration is for application deployment as container.

For container registry access the following variables are required to be set.
The command below expects these in a file `credentials.hcl`
(See https://developer.hashicorp.com/nomad/docs/job-specification/hcl2/variables[variables]).

* `registry_auth_username`
* `registry_auth_password`

=== Local


.Set nomad environment
[source,bash]
----
include::local-container-app-env.sh[]
----
Run `. ./local-container-app-env.sh`

.Deployment

.Deployment
[source,bash]
----
include::container-app-run.sh[]
----
Run `./container-app-run.sh`

.Open application
[source,bash]
----
open "http://continuousdelivery-api-${NOMAD_NAMESPACE}.$(ipconfig getifaddr en0).nip.io:80/api/"
----

=== Google cloud platform

.Set nomad environment
[source,bash]
----
include::gcp-container-app-env.sh[]
----
Run `. ./gcp-container-app-env.sh`


.Deployment
[source,bash]
----
include::container-app-run.sh[]
----
Run `./container-app-run.sh`

.Open application
[source,bash]
----
open "http://continuousdelivery-api-${NOMAD_NAMESPACE}.${NOMAD_VAR_api_service_domain}:80/api/"
----



== Deploy native application

.exec driver configuration
[source,hcl]
----
driver = "${var.api_task_driver}"
config {
    command = "continuousdelivery"
}
artifact {
    source = "https://gitlab.com/api/v4/projects/14961729/packages/maven/at/martinahrer/${var.artifact_name}/${var.artifact_version}/${var.artifact_name}-${var.artifact_version}-${var.artifact_classifier}"
    headers {
        PRIVATE-TOKEN = "${var.repository_private_token}"
    }
    options {
        filename = "${var.artifact_name}"
        checksum = "${var.artifact_checksum}"
    }
}
----

This driver configuration requires a GitLab private token to be present as variable `repository_private_token` (e.g. by adding to `credentials.hcl`).

=== Run with exec driver

.`exec-configuration.hcl`
[source,bash]
----
include::exec-configuration.hcl[]
----

==== Local

.Set nomad environment
[source,bash]
----
include::local-native-app-env.sh[]
----
Run `. ./local-native-app-env.sh`

.Deployment
[source,bash]
----
include::native-app-run.sh[]
----
Run `./native-app-run.sh`

.Deployment
[source,bash]
----
export NOMAD_VAR_api_service_domain="$(ipconfig getifaddr en0).nip.io"
export NOMAD_NAMESPACE="bootiful-native"
nomad namespace apply "${NOMAD_NAMESPACE}"
nomad job run --var environment="${NOMAD_NAMESPACE}" --namespace="${NOMAD_NAMESPACE}" --var-file configuration.hcl --var-file credentials.hcl  --var-file exec-configuration.hcl continuousdelivery.hcl
----

.Open application
[source,bash]
----
open "http://continuousdelivery-api-${NOMAD_NAMESPACE}.${NOMAD_VAR_api_service_domain}:80/api/"
----

==== Google cloud platform

.Set nomad environment
[source,bash]
----
include::gcp-native-app-env.sh[]
----
Run `. ./gcp-native-app-env.sh`


.Deployment
[source,bash]
----
include::native-app-run.sh[]
----
Run `./native-app-run.sh`


.Open application
[source,bash]
----
open "http://continuousdelivery-api-${NOMAD_NAMESPACE}.${NOMAD_VAR_api_service_domain}:80/api/"
----

=== Run with raw-exec driver

A nomad client agent with the `raw_exec` driver enabled is required
(see https://developer.hashicorp.com/nomad/docs/drivers/raw_exec#client-requirements).

.`darwin-raw-exec-configuration.hcl`
[source,bash]
----
include::darwin-raw-exec-configuration.hcl[]
----

.Deployment
[source,bash]
----
export NOMAD_VAR_api_service_domain="$(ipconfig getifaddr en0).nip.io"
export NOMAD_NAMESPACE="raw-exec-workload"
nomad namespace apply "${NOMAD_NAMESPACE}"
nomad job run --var environment="${NOMAD_NAMESPACE}" --namespace="${NOMAD_NAMESPACE}" --var-file configuration.hcl --var-file credentials.hcl  --var-file darwin-raw-exec-configuration.hcl continuousdelivery.hcl
----

.Open application
[source,bash]
----
open "http://continuousdelivery-api-${NOMAD_NAMESPACE}.${NOMAD_VAR_api_service_domain}:80/api/"
----


== Deploy Java workload

A nomad client agent with the `java` driver enabled is required (Java 17+)

.Java driver configuration
[source,hcl]
----
driver = "${var.api_task_driver}"
config {
    jar_path = "local/${local.artifact_filename}"
}
----

.`java-configuration.hcl`
----
include::java-configuration.hcl[]
----

=== Local

.Deployment
[source,bash]
----
export NOMAD_VAR_api_service_domain="$(ipconfig getifaddr en0).nip.io"
export NOMAD_NAMESPACE="java-workload"
nomad namespace apply "${NOMAD_NAMESPACE}"
nomad job run --var environment="${NOMAD_NAMESPACE}" --namespace="${NOMAD_NAMESPACE}" --var-file configuration.hcl --var-file credentials.hcl  --var-file java-configuration.hcl continuousdelivery.hcl
----

.Open application
[source,bash]
----
open "http://continuousdelivery-api-${NOMAD_NAMESPACE}.${NOMAD_VAR_api_service_domain}:80/api/"
----

=== Google cloud platform

.Set nomad environment
[source,bash]
----
include::gcp-native-app-env.sh[]
----
Run `. ./gcp-java-app-env.sh`


.Deployment
[source,bash]
----
include::java-app-run.sh[]
----
Run `./java-app-run.sh`

.Open application
[source,bash]
----
open "http://continuousdelivery-api-${NOMAD_NAMESPACE}.${NOMAD_VAR_api_service_domain}:80/api/"
----

