= README


== Runtime infrastructure

== Consul + Nomad

=== Local development instances

Run consul and nomad service from repository (TODO).
Run as many Nomad clients as required.
However, when running multiple clients you will not be able to deploy traefik to all client nodes as the traefik job configuration tries to do a static port binding.

=== Remote development instances (cluster)

Setup cluster according to https://github.com/MartinAhrer/learn-nomad-cluster-setup and https://developer.hashicorp.com/nomad/tutorials/cluster-setup.

.Install software
[source,bash]
----
brew install packer
brew install terraform
brew install --cask google-cloud-sdk
----

==== Google cloud

. Setup gcloud
[source,bash]
----
gcloud auth login
gcloud config set project ***
gcloud config set compute/region ***
gcloud config set compute/zone ***
----

== Deploy traefik

----
docker container run --rm -ti -v ${PWD}:/levant --workdir /levant -e NOMAD_ADDR=http://localhost:4646 hashicorp/levant:0.3.1 levant deploy traefik.hcl
----

== Deploy container application

Default configuration is for application deployment as container.

For container registry access the following variables are required to be set.
The command below expects these in a file `credentials.hcl`
(See https://developer.hashicorp.com/nomad/docs/job-specification/hcl2/variables[variables]).

* `registry_auth_username`
* `registry_auth_password`

.Deployment commands
[source,bash]
----
export NOMAD_NAMESPACE="${$(git rev-parse --abbrev-ref HEAD)//\//-}"
nomad namespace apply "${NOMAD_NAMESPACE}"
nomad job run --var environment="${NOMAD_NAMESPACE}" --namespace="${NOMAD_NAMESPACE}" --var-file configuration.hcl --var-file credentials.hcl continuousdelivery.hcl
----



