providers:
    consulCatalog: # https://doc.traefik.io/traefik/providers/consul-catalog/#traefik-consul-catalog
        exposedByDefault: false # services need a traefik.enable=true tag
        endpoint:
            address: {{ env "CONSUL_SOCKET_ADDRESS" }}
            token: {{ env "CONSUL_HTTP_TOKEN" }}
        prefix: traefik # the default
        constraints: "Tag(`traefik.tags=service`)"

api:
    dashboard: true
    insecure: true # TODO Will it be available through https ?

ping:
    entryPoint: "traefik"

entryPoints:
    http:
        address: {{ env "NOMAD_PORT_http" | printf ":%s" }}
    traefik:
        address: {{ env "NOMAD_PORT_api" | printf ":%s" }}

log:
    level: DEBUG
